config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }, :path => "blog",
    :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :password => 'secret',
    :confirmation => 'verification',
    :unlock => 'unblock',
    :registration => 'register',
    :sign_up => 'blog-with-yinka' }

  get 'hire', to: 'contacts#new'
  
  resources :contacts, only: [:new, :create], :path => "hire"

  resources :articles do
    resources :comments
  end

  get 'about', to: 'static_pages#about'
  get 'services', to: 'static_pages#services'


  root 'static_pages#index'


end

app/models/comment.rb
class Comment < ApplicationRecord
	default_scope { order('created_at DESC') }
  belongs_to :article
  belongs_to :user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
	before_action :find_article
	before_action :find_comment, only: [:edit, :update, :destroy]
	
	def create
		@comment = @article.comments.create(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			flash[:success] = "Comment successfully posted!"
			redirect_to article_path(@article)
		else
			flash[:danger] = "Please check error(s) marked red!"
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @comment.update(comment_params)
			flash[:success] = "Comment has been updated successfully"
			redirect_to article_path(@article)
		else
			flash[:danger] = "Please check error(s) marked red!"
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		flash[:success] = "Comment has been successfully deleted!"
		redirect_to article_path(@article)
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

	def find_article
		@article = Article.find(params[:article_id])
	end

	def find_comment
		@comment = @article.comments.find(params[:id])
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
 <div class="panel panel-default">
  <div class="panel-body">
      <p>Comment by: <small><strong><%= comment.user.firstname -%></strong> <%= time_ago_in_words(comment.created_at) -%> ago</small></p>
        <%= raw (comment.content) %>

   <% if user_signed_in? -%>
    <% if comment.user_id == current_user.id -%>
    <div class="blog-buttons">
      <%= link_to "Edit Comment", edit_article_comment_path(comment.article, comment), class: "btn btn-warning btn-sm" %>
     	 <%= link_to "Delete Comment", article_comment_path(comment.article, comment), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger btn-sm" %>
    </div>

    <% end -%>
  <% end -%>
  </div>
   
</div>

app/views/comments/_form.html.erb
<%= bootstrap_form_for ([@article, Comment.new]) do |f| %>
  <%= f.text_area :content, label: "Post Comment", placeholder: "Post Comments Here...", rows: "10" %>
  <%= f.submit class: "btn btn-success" %>
  <%= link_to "Cancel", articles_path, class: "btn btn-danger" %>
<% end -%>

app/views/comments/edit.html.erb
 


<div class="container">
	<h2 class="text-center">Edit Comments</h2>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= bootstrap_form_for ([@article, @comment]) do |f| %>
			  <%= f.text_area :content, label: "Post Comment", placeholder: "Post Comments Here...", rows: "10", class: "wysihtml5" %>
			  <%= f.submit class: "btn btn-success" %>
			  <%= link_to "Cancel", articles_path, class: "btn btn-danger" %>
			<% end -%>
		</div>
	</div>
</div>