config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }, :path => "blog",
    :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :password => 'secret',
    :confirmation => 'verification',
    :unlock => 'unblock',
    :registration => 'register',
    :sign_up => 'blog-with-yinka' }

  get 'hire', to: 'contacts#new'
  
  resources :contacts, only: [:new, :create], :path => "hire"

  resources :articles do
    resources :comments
  end

  get 'about', to: 'static_pages#about'
  get 'services', to: 'static_pages#services'


  root 'static_pages#index'


end

app/views/layouts/_blog.html.erb
<body id="blog">

  <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class:"navbar-brand" do %>
            <i class="fa fa-usd"><strong>i_am = "Yinka Ash"</strong></i>
          <% end -%>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= current_page?(root_path) ? "active" : "" %>"><%= link_to "Home", root_path %></li>
            <li class="<%= current_page?(services_path) ? "active" : "" %>"><%= link_to "Services", services_path %></li>
            <li class="<%= current_page?(about_path) ? "active" : "" %>"><%= link_to "About", about_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="<%= current_page?(hire_path) ? "active" : "" %> specialBtn"><%= link_to "Hire Yinka", hire_path %></li>
            

             <% if user_signed_in? -%>
             <li><%= link_to "Log Out", destroy_user_session_path, method: :delete  %></li>
            <% else -%>
              <li class="<%= current_page?(articles_path) ? "active" : "" %>"><%= link_to "Blog", articles_path %></li>
            <% end -%>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

   <section>
     <div class="container">
     <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "flash alert alert-#{key}" %>
      <% end %>
        <%= yield %>
     </div>
   </section>

    <footer>
    <hr>
   <div class="container">
     <p class="text-center">&copy; 2017. Creative Design By: <%= link_to "Yinka Ash", 'http://iamyinka.com', title: "Yinka's Website", class: "btn btn-link" %></p>
   </div> 
  </footer>

  
  
  </body>

app/views/layouts/_more_static.html.erb
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class:"navbar-brand" do %>
            <i class="fa fa-usd"><strong>i_am = "Yinka Ash"</strong></i>
          <% end -%>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= current_page?(root_path) ? "active" : "" %>"><%= link_to "Home", root_path %></li>
            <li class="<%= current_page?(services_path) ? "active" : "" %>"><%= link_to "Services", services_path %></li>
            <li class="<%= current_page?(about_path) ? "active" : "" %>"><%= link_to "About", about_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="<%= current_page?(hire_path) ? "active" : "" %> specialBtn"><%= link_to "Hire Yinka", hire_path %></li>
             <li class="<%= current_page?(articles_path) ? "active" : "" %>"><%= link_to "Blog", articles_path  %></li>
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <section class="page-heading">
      <div class="container-fluid">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "flash alert alert-#{key}" %>
      <% end %>
        <%= yield %>
      </div>
    </section>

    <footer>
    <hr>
   <div class="container-fluid">
     <p class="text-center">&copy; 2017. Creative Design By: <%= link_to "Yinka Ash", 'http://iamyinka.com', title: "Yinka's Website", class: "btn btn-link" %></p>
   </div> 
  </footer>
  </body>

app/views/layouts/_static_pages.html.erb
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> 
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class:"navbar-brand" do %>
            <i class="fa fa-usd"><strong>i_am = "Yinka Ash"</strong></i>
          <% end -%>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= current_page?(root_path) ? "active" : "" %>"><%= link_to "Home", root_path %></li>
            <li class="<%= current_page?(services_path) ? "active" : "" %>"><%= link_to "Services", services_path %></li>
            <li class="<%= current_page?(about_path) ? "active" : "" %>"><%= link_to "About", about_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
          	<li class="<%= current_page?(hire_path) ? "active" : "" %> specialBtn"><%= link_to "Hire Yinka", hire_path %></li>
              <li class="<%= current_page?(articles_path) ? "active" : "" %>"><%= link_to "Blog", articles_path %></li>
            <!-- end -->
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <header>
      <div class="container-fluid">
        <div class="header-content">
          <h1>I am Yinka Ash</h1>
          <p><em>... A front &amp; back-end Web developer based in Kuala Lumpur, Malaysia. <br>
          <span>UI Designer</span> by day &amp; <span>Developer</span> by night. I never sleep... almost.</em>
          </p>
          <%= link_to "Read More About Me >>", about_path, title: "Read More About Me", class: "btn btn-custom" %>
          <%= link_to "Skill Set >>", services_path, title: "My Skill Set", class: "btn btn-custom" %>
        </div>
      </div>
    </header>

    <section>
      <div class="container">
        <%= yield %>
      </div>
    </section>
    
  <footer>
    <hr>
   <div class="container-fluid">
     <p class="text-center">&copy; 2017. Creative Design By: <%= link_to "Yinka Ash", 'http://iamyinka.com', title: "Yinka's Website", class: "btn btn-link" %></p>
   </div> 
  </footer>

  </body>

app/views/layouts/application.html.erb
<% provide(:title, '') %>

<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | Yinka Ash</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  
  	<% if current_page?(root_path) %>
	    <%= render 'layouts/static_pages' %>
    <% elsif current_page?(services_path) || current_page?(about_path) -%>
    	<%= render 'layouts/more_static' %>
  	<% else -%>
  		<%= render 'layouts/blog' %>
	  <% end %>
   
  
</html>